swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  # Routes utilisateur
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update User Profile
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  # Routes transaction
  /transactions/current-month:
    get:
      tags:
        - Transactions
      summary: Retrieve all transactions for the current month
      description: Returns a list of all transactions for the current month, grouped by account
      security:
        - Bearer: []
      parameters:
        - in: query
          name: accountId
          description: Filter transactions by account ID (optional)
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: List of transactions for the current month retrieved successfully
          schema:
            type: object
            properties:
              transactions:
                type: array
                items:
                  $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Retrieve details of a specific transaction
      description: Returns detailed information about a specific transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionDetail'
        '404':
          description: Transaction not found
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

    put:
      tags:
        - Transactions
      summary: Update an existing transaction
      description: Allows updating details of an existing transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Updated transaction details
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /transactions:
    post:
      tags:
        - Transactions
      summary: Add a new transaction
      description: Allows the addition of a new transaction
      security:
        - Bearer: []
      parameters:
        - in: body
          name: body
          description: Transaction payload to be added
          required: true
          schema:
            $ref: '#/definitions/TransactionCreate'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction added successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

definitions:
  User:
    type: object
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name

  Login:
    type: object
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      userName:
        type: string

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      accountId:
        type: string
        description: Account ID associated with the transaction
      description:
        type: string
        description: Description of the transaction

  TransactionDetail:
    allOf:
      - $ref: '#/definitions/Transaction'
      - type: object
        properties:
          details:
            type: string
            description: Detailed description or additional information about the transaction

  TransactionCreate:
    type: object
    properties:
      amount:
        type: number
        format: float
        description: Amount of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      accountId:
        type: string
        description: Account ID associated with the transaction
      description:
        type: string
        description: Description of the transaction

  TransactionUpdate:
    type: object
    properties:
      amount:
        type: number
        format: float
        description: Updated amount of the transaction
      date:
        type: string
        format: date
        description: Updated date of the transaction
      description:
        type: string
        description: Updated description of the transaction

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
